defaults:
#  - client: classical
#  - federated_strategy: classical
#  - client: classical-small-batch
#  - federated_strategy: classical-small-batch
#  - client: fed-two-clients
#  - federated_strategy: fed-two-clients
#  - client: fed-full-clients
#  - federated_strategy: fed-full-clients
#  - client: two-test
#  - federated_strategy: two-test

# more classical fedavg with no scheduler but constant lr
#  - client: classical-no-sched
#  - federated_strategy: classical
#  - client: fed-two-clients-no-sched
#  - federated_strategy: fed-two-clients
  - client: fed-full-clients-no-sched
  - federated_strategy: fed-full-clients