defaults:
#  - client: classical
#  - federated_strategy: classical
#  - client: classical-small-batch
#  - federated_strategy: classical-small-batch
  - client: fed-two-clients
  - federated_strategy: fed-two-clients
#  - client: full-two-clients
#  - federated_strategy: full-two-clients


