defaults:
#  - client: classical
  - client: classical-small-batch
#  - client: federated-two-clients
#  - federated_strategy: classical
  - federated_strategy: classical-small-batch
#  - federated_strategy: federated-two-clients


