defaults:
####
# IID
####
# done
#  - client: iid_classical
#  - federated_strategy: iid_classical

  - client: iid_fed-full-clients
  - federated_strategy: iid_fed-full-clients

#  - client: iid_fed-two-clients
#  - federated_strategy: iid_fed-two-clients


####
# Non-IID
####
#  - client: noniid_classical
#  - federated_strategy: noniid_classical

# done
#  - client: noniid_fed-full-clients
#  - federated_strategy: noniid_fed-full-clients

#  - client: noniid_fed-two-clients
#  - federated_strategy: noniid_fed-two-clients
