defaults:
####
# IID
####
# done
#  - client: iid_classical
#  - federated_strategy: iid_classical

# done
#  - client: iid_fed-full-clients
#  - federated_strategy: iid_fed-full-clients

  - client: iid_fed-full-clients-stretched-out
  - federated_strategy: iid_fed-full-clients-stretched-out

#  - client: iid_fed-two-clients
#  - federated_strategy: iid_fed-two-clients


####
# Non-IID
####
#  - client: noniid_classical
#  - federated_strategy: noniid_classical

# done
#  - client: noniid_fed-full-clients
#  - federated_strategy: noniid_fed-full-clients

#  - client: noniid_fed-full-clients-stretched-out
#  - federated_strategy: noniid_fed-full-clients-stretched-out

#  - client: noniid_fed-two-clients
#  - federated_strategy: noniid_fed-two-clients
