training:
  num_total_clients: 1 # simulating on one client
  epoch_per_round: 1
  data_per_speaker: 30 # 10 sampless nativle plus 20 more agumented with speed pertubation
  speaker_per_client: 462
  batch_size: 30
  num_workers: 8
  accumulate_grad_batches: 7 # for 7 clients simulation

validation:
  batch_size: 8
  num_workers: 8

augment:
  freq_mask: 3
  time_mask: 8
  speed_pertubation: True

model:
  optim:
    type: SGD
    initial_lr: 0.00005 # 5e-5
    sched:
      type: "none"
